---
.gitignore:
  paths:
  - SSH_I_DUMPED
.rubocop.yml:
  include_todos: true
  default_configs:
    Metrics/BlockNesting:
      Max: 4
Gemfile:
  optional:
    ':default':
      - gem: 'backport_dig'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.3.0')"
      - gem: 'puppetmodule-netdev_stdlib'
        git: 'https://github.com/puppetlabs/netdev_stdlib.git'
        from_env: true
      - gem: 'net-ssh-telnet'
    ':development':
      - gem: 'codecov'
      - gem: 'puppet-resource_api'
      - gem: 'simplecov-console'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: 'master'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
    ':system_tests':
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: beaker
        version: '>= 3'
        from_env: 'BEAKER_VERSION'
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
      - gem: beaker-abs
        from_env: 'BEAKER_ABS_VERSION'
        version: '~> 0.1'
      - gem: puppet-blacksmith
        version: '~> 3.4'
      - gem: yard
      - gem: puppet-strings
Rakefile:
  requires:
    - 'github_changelog_generator/task'
  extras:
    - |
      if Bundler.rubygems.find_name('github_changelog_generator').any?
        GitHubChangelogGenerator::RakeTask.new :changelog do |config|
          config.user = 'puppetlabs'
          config.project = 'cisco_ios'
          config.since_tag = '0.1.0'
          config.future_release = '0.1.1'
          config.exclude_labels = ['maintenance']
          config.header = "# Change log\n\nAll notable changes to this project will be documented in this file. The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) and this project adheres to [Semantic Versioning](http://semver.org)."
          config.add_pr_wo_labels = true
          config.issues = false
          config.merge_prefix = "### UNCATEGORIZED PRS; GO LABEL THEM"
          config.configure_sections = {
            "Changed" => {
              "prefix" => "### Changed",
              "labels" => ["backwards-incompatible"],
            },
            "Added" => {
              "prefix" => "### Added",
              "labels" => ["feature", "enhancement"],
            },
            "Fixed" => {
              "prefix" => "### Fixed",
              "labels" => ["bugfix"],
            },
          }
        end
      end
spec/spec_helper.rb:
  mock_with: ':rspec'
