---
.gitignore:
  paths:
  - SSH_I_DUMPED
.rubocop.yml:
  include_todos: true
  default_configs:
    Metrics/BlockNesting:
      Max: 4
.travis.yml:
  simplecov: true
Gemfile:
  optional:
    ':default':
      - gem: 'backport_dig'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.3.0')"
      - gem: 'puppetmodule-netdev_stdlib'
        git: 'https://github.com/puppetlabs/netdev_stdlib.git'
        from_env: true
      - gem: 'net-ssh-telnet'
    ':development':
      - gem: 'codecov'
      - gem: 'puppet-resource_api'
      - gem: 'simplecov-console'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: 'master'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
    ':system_tests':
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: beaker
        version: '< 4'
        from_env: 'BEAKER_VERSION'
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
      - gem: beaker-abs
        from_env: 'BEAKER_ABS_VERSION'
        version: '~> 0.1'
      - gem: puppet-blacksmith
        version: '~> 3.4'
      - gem: yard
      - gem: puppet-strings
spec/spec_helper.rb:
  mock_with: ':rspec'
Rakefile:
  changelog_user: 'puppetlabs'
  changelog_project: 'cisco_ios'
